### ISSUE TITLE
Support of YAML instead of JSON

### ISSUE THREAD

**Issue by stefc** [kl1mm/localize#3]
What about using YAML format instead of Json for defining the localizations. 
```
default: de

languages: 
  - de: 
    - MyText: Hallo Welt (German)

  - en: 
	  - MyText: Hello World (English)
```

**Comment by kl1mm** [comment]
Hi Stefc,
at the moment there are no plans to extend this project to also use YAML as source for the strings to be localized. We may consider it if there are others who are also interested in this feature.

Best Regards mMilk

**Comment by devfinnd** [comment]
I'd also be interested in YAML support, mainly because it would be way more convenient to edit than multiple JSON files.

```yaml
locale:
  default_locale: "de_DE"
  hello_world:
    en_US: "Hello World"
    de_DE: "Hallo Welt"
  bye_world:
    en_US: "Bye World"
    de_DE: "Tschüss Welt"
```
